plugins {
	id 'com.diffplug.spotless' version '8.10.2' apply false
}

allprojects {

	apply plugin: 'idea'
	apply plugin: 'eclipse'
	apply plugin: 'com.diffplug.spotless'

	spotless {
		java {
			target 'src/*/java/**/*.java'
			googleJavaFormat()
			removeUnusedImports()
			importOrder()
			trimTrailingWhitespace()
			endWithNewline()
		}
	}

	repositories {
		mavenCentral()
		maven { url 'https://repo.spring.io/release' }
		maven { url 'https://repo.spring.io/milestone' }
		maven { url 'https://repo.spring.io/snapshot' }
		maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }

	}

	ext {
		set('springAiVersion', "2.0.1")
	}

	tasks.withType(JavaExec) {
		jvmArgs = ['--enable-native-access=ALL-UNNAMED']
	}

	tasks.withType(Test) {
		jvmArgs = ['--enable-native-access=ALL-UNNAMED']
	}
}
